## numpy

In [3]:
import numpy as np
import pandas as pd

In [36]:
km = [44410., 5712., 37123., 12300., 25757.]
anos = [2003, 1991, 1990, 2017, 2006]


In [37]:
idade = 2022 - anos # com arry numpy essa operação é suportada.
idade

TypeError: unsupported operand type(s) for -: 'int' and 'list'

In [38]:
km = np.array([44410., 5712., 37123., 12300., 25757.])
anos = np.array([2003, 1991, 1990, 2017, 2006])

In [39]:
idade = 2019 - anos
idade

array([16, 28, 29,  2, 13])

## Operações entre arrays

In [40]:
km_media = km / idade
km_media

array([2775.625     ,  204.        , 1280.10344828, 6150.        ,
       1981.30769231])

## Operações com array de duas dimensões

In [41]:
dados = np.array([km, idade]) 
df = pd.DataFrame(dados)
df

0       1        2        3        4
0  44410.0  5712.0  37123.0  12300.0  25757.0
1     16.0    28.0     29.0      2.0     13.0

In [66]:
dados.shape

(2, 5)

In [60]:
dados[0]

array([44410.,  5712., 37123., 12300., 25757.])

In [61]:
dados[1]

array([16., 28., 29.,  2., 13.])

In [63]:
km_media = dados[0] / dados[1] 
km_media

array([2775.625     ,  204.        , 1280.10344828, 6150.        ,
       1981.30769231])

## seleções com numpy

In [72]:
peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])
IMC = peso / (altura * altura)
IMC

array([29.36288089, 29.26224956, 24.48979592])

In [73]:
peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])
IMC = peso / altura ** 2
IMC

array([29.36288089, 29.26224956, 24.48979592])

In [18]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteira', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casada', 'feminino']
    ]
)

In [19]:
selecao = dados == 'masculino' 
selecao

array([[False, False,  True],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

In [31]:
dados[0::2]# a cada (:) muda o criterio logo o primeiro numero é o start, o 2º valor é o stop, vazio vai ate o fim e o 3º valor é o intervalo

array([['Roberto', 'casado', 'masculino'],
       ['Bruno', 'solteiro', 'masculino']], dtype='<U9')

In [32]:
dados[0::2, :2]#oque tiver antes da vircula representa linha oque tiver depois coluna

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

## Atributos do numpy

In [42]:
dados.dtype

dtype('float64')

In [43]:
dados.T

array([[4.4410e+04, 1.6000e+01],
       [5.7120e+03, 2.8000e+01],
       [3.7123e+04, 2.9000e+01],
       [1.2300e+04, 2.0000e+00],
       [2.5757e+04, 1.3000e+01]])

In [44]:
dados.transpose()

array([[4.4410e+04, 1.6000e+01],
       [5.7120e+03, 2.8000e+01],
       [3.7123e+04, 2.9000e+01],
       [1.2300e+04, 2.0000e+00],
       [2.5757e+04, 1.3000e+01]])

## Metodos numpy

In [4]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteira', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casada', 'feminino']
    ]
)

In [5]:
dados.tolist()# transforma o array numpy em uma lista do python

[['Roberto', 'casado', 'masculino'],
 ['Sheila', 'solteira', 'feminino'],
 ['Bruno', 'solteiro', 'masculino'],
 ['Rita', 'casada', 'feminino']]

In [6]:
dados.reshape((1,12))#coloca 12 resultados em um array numpy

array([['Roberto', 'casado', 'masculino', 'Sheila', 'solteira',
        'feminino', 'Bruno', 'solteiro', 'masculino', 'Rita', 'casada',
        'feminino']], dtype='<U9')

In [55]:
km = [44410., 5712., 37123., 12300., 25757.]
anos = [2003, 1991, 1990, 2017, 2006]

In [56]:
dados = km + anos
dados

[44410.0, 5712.0, 37123.0, 12300.0, 25757.0, 2003, 1991, 1990, 2017, 2006]

In [64]:
dados = np.array(dados).reshape((2, 5))#o reshape reorganiza a ordem de exibição dos valores, nesse caso 2 linha e 5 colunas

In [61]:
np.array(dados).reshape((5, 2), order = 'C')

array([[44410.,  5712.],
       [37123., 12300.],
       [25757.,  2003.],
       [ 1991.,  1990.],
       [ 2017.,  2006.]])

In [62]:
np.array(dados).reshape((5, 2), order = 'F')

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [12300.,  2017.],
       [25757.,  2006.]])

In [65]:
dados2 = dados.copy() 
dados2

array([[44410.,  5712., 37123., 12300., 25757.],
       [ 2003.,  1991.,  1990.,  2017.,  2006.]])

In [68]:
dados2.resize((3, 5), refcheck=False)
dados2

array([[44410.,  5712., 37123., 12300., 25757.],
       [ 2003.,  1991.,  1990.,  2017.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [81]:
dados2.size

15

In [69]:
dados2[2] = dados[0]/(2022 - dados[1] )

In [80]:
df = pd.DataFrame(dados2, index = ('KM', 'Ano', 'KM_Media'), columns = ('Carro01','Carro02','Carro03','Carro04','Carro05')).round(2)
df

Carro01  Carro02   Carro03  Carro04   Carro05
KM        44410.00  5712.00  37123.00  12300.0  25757.00
Ano        2003.00  1991.00   1990.00   2017.0   2006.00
KM_Media   2337.37   184.26   1160.09   2460.0   1609.81

## Estatistica com numpy

In [7]:
import numpy as np
import pandas as pd

In [8]:
km = np.loadtxt('C:/Users/gabri/Documents/python/Data-science/Alura/Python Pandas/Numpy/data/carros-km.txt')
anos = np.loadtxt('C:/Users/gabri/Documents/python/Data-science/Alura/Python Pandas/Numpy/data/carros-anos.txt')
valor = np.loadtxt('C:/Users/gabri/Documents/python/Data-science/Alura/Python Pandas/Numpy/data/carros-valor.txt')

In [11]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [10]:
dataset.shape

(258, 3)

In [95]:
np.mean(dataset, axis = 0)#essa função verifica a media de cada coluna

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [99]:
np.std(dataset[:,1:], axis = 0)# essa função pega o desvio padrao das colunas

array([39859.82699005, 29754.10115039])

In [101]:
dataset[:,1:].sum(axis = 0)# essa função soma todas as linhas das colunas

array([11480849.        , 25531812.37999999])

In [103]:
np.sum(dataset[:,1:], axis = 0)# essa daqui assim como a media usa o metodo.

array([11480849.        , 25531812.37999999])

In [106]:
idades = np.array([10, 23, 45, 34, 25])
np.sum(idades) / idades.size

137