In [2]:
import numpy as np

matriz_1 =  np.array([[7.0, 8.0],[5.0, 1.0]])
matriz_2 = np.array([[3.0, 4.0],[4.0, 2.0]])

# Soma de matrizes
print(matriz_1 + matriz_2)



[[10. 12.]
 [ 9.  3.]]


In [3]:
# Subtração de matrizes
print(matriz_1 - matriz_2)


[[ 4.  4.]
 [ 1. -1.]]


In [4]:
# Multiplicação de Matrizes
print(matriz_1 * matriz_2)


[[21. 32.]
 [20.  2.]]


In [5]:
# Divisão de Matrizes
print(matriz_1 / matriz_2)

[[2.33333333 2.        ]
 [1.25       0.5       ]]


In [10]:
import collections

dias_da_semana = collections.deque(["Dom","Seg","Ter","Qua","Qui","Sex","Sab"])
dias_da_semana

deque(['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'])

In [11]:
dias_da_semana.append("Janeiro")
dias_da_semana

deque(['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab', 'Janeiro'])

In [12]:
dias_da_semana.popleft()
dias_da_semana

deque(['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab', 'Janeiro'])

In [13]:
dias_da_semana.pop()
dias_da_semana

deque(['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'])

In [14]:
dias_da_semana.appendleft("Dom")
dias_da_semana

deque(['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'])